"""new changes to home, added url

Revision ID: 823f9fa707f3
Revises: 16f25443b6ec
Create Date: 2019-08-07 16:53:06.589213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823f9fa707f3'
down_revision = '16f25443b6ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home', sa.Column('url', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('home', 'url')
    # ### end Alembic commands ###
